import test from 'node:test';
import assert from 'node:assert/strict';
import {parseDate as dt,isoDate,WorkCalendar,DAY,inverseLagUpper,addLag} from '../src/core/calendar.js';
import {Scheduler,createBaseline,compareSchedules} from '../src/core/scheduler.js';
import {emptyProject,createDemoProject,defaultCalendars} from '../src/core/sample.js';
import {buildGraph,validateProject,validateWorkbook,History} from '../src/core/model.js';
import {analyzeResources} from '../src/core/resources.js';
import {toCSV,parseCSV} from '../src/core/storage.js';

const office=()=>new WorkCalendar(defaultCalendars()[0]);
function project(){const p=emptyProject('Test project','test');p.start=dt('2026-07-06T08:00');p.dataDate=p.start;return p;}
function activity(id,days=1,extra={}){return {id,code:id,name:id,wbsId:'wbs-1',calendarId:'cal-office',type:days===0?'milestone':'task',duration:days*480,remaining:days*480,percent:0,actualStart:null,actualFinish:null,constraint:'none',constraintDate:null,notes:'',...extra};}
function link(from,to,type='FS',lag=0){return {id:from+'-'+to+'-'+type,from,to,type,lag};}
function schedule(p){return new Scheduler().schedule(p);}
function result(s,id){return s.activities.find(a=>a.id===id);}
function near(actual,expected,tolerance=1e-9){assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} != ${expected}`);}

test('Civil dates round-trip without host timezone conversion',()=>{assert.equal(isoDate(dt('2026-03-29T02:30')),'2026-03-29T02:30');assert.equal(isoDate(dt('2026-07-06')),'2026-07-06T00:00');});
test('Malformed, impossible and timezone-qualified dates are rejected',()=>{for(const value of ['2026-02-30','2026-13-01','2026-01-01T24:01','2026-07-06T08:00Z','junk',1.2,1e14])assert.throws(()=>dt(value));});
test('Split shift addition skips the lunch break',()=>{assert.equal(isoDate(office().add(dt('2026-07-06T11:00'),120)),'2026-07-06T14:00');});
test('Whole workday finish is an end boundary, not next workday start',()=>{assert.equal(isoDate(office().add(dt('2026-07-06T08:00'),480)),'2026-07-06T17:00');});
test('Positive working duration skips weekends',()=>{assert.equal(isoDate(office().add(dt('2026-07-10T16:00'),120)),'2026-07-13T09:00');});
test('Negative working duration crosses lunch and weekend correctly',()=>{assert.equal(isoDate(office().add(dt('2026-07-13T09:00'),-120)),'2026-07-10T16:00');assert.equal(isoDate(office().add(dt('2026-07-06T14:00'),-120)),'2026-07-06T11:00');});
test('Holiday exceptions replace weekly shifts',()=>{const c=office();assert.equal(isoDate(c.add(dt('2026-08-28T16:00'),120)),'2026-09-01T09:00');});
test('Partial-day exception replaces all usual intervals',()=>{const d=defaultCalendars()[0];d.exceptions['2026-07-07']=[[600,660]];const c=new WorkCalendar(d);assert.equal(isoDate(c.add(dt('2026-07-06T16:00'),180)),'2026-07-08T09:00');});
test('Working differences are signed, additive, and exclude gaps',()=>{const c=office(),a=dt('2026-07-10T16:00'),b=dt('2026-07-13T09:00'),m=dt('2026-07-11T00:00');assert.equal(c.between(a,b),120);assert.equal(c.between(b,a),-120);assert.equal(c.between(a,m)+c.between(m,b),120);});
test('Milestones may sit at a workday finish boundary',()=>{const c=office(),t=dt('2026-07-06T17:00');assert.equal(c.pointUp(t),t);assert.equal(c.pointDown(t),t);assert.equal(isoDate(c.startUp(t)),'2026-07-07T08:00');});
test('Finish lower-bound inversion is exact at lunch and weekend discontinuities',()=>{const c=office();for(const [target,duration] of [['2026-07-06T13:00',240],['2026-07-13T08:00',480],['2026-07-13T18:00',480]]){const cap=dt(target),s=c.earliestStartForFinish(cap,duration);assert.ok(c.add(s,duration)>=cap);const previous=c.startDown(s-1);assert.ok(c.add(previous,duration)<cap);}});
test('Finish upper-bound inversion is maximal on the working-minute lattice',()=>{const c=office();for(const target of ['2026-07-06T13:00','2026-07-13T08:00','2026-07-13T18:00']){const cap=dt(target),s=c.latestStartForFinish(cap,480);assert.ok(c.add(s,480)<=cap);assert.ok(c.add(c.startUp(s+1),480)>cap);}});
test('Negative-lag inversion includes nonworking plateaus',()=>{const c=office(),target=dt('2026-07-10T08:00'),bound=inverseLagUpper(target,-480,c);assert.equal(isoDate(bound),'2026-07-13T08:00');assert.equal(c.add(bound,-480),target);assert.ok(c.add(bound+1,-480)>target);});
test('Lag inversion satisfies its greatest-integer postcondition for signed offsets',()=>{const c=office();for(const target of ['2026-07-06T08:00','2026-07-10T17:00','2026-07-11T12:00','2026-07-13T13:00'])for(const lag of [-960,-480,-60,-1,0,1,60,480,960]){const t=dt(target),u=inverseLagUpper(t,lag,c);assert.ok(addLag(u,lag,c)<=t,`${target},${lag}`);assert.ok(addLag(u+1,lag,c)>t,`${target},${lag}: upper bound is not maximal`);}});
test('Overlapping shifts and calendars with no recurring work are rejected',()=>{const d=defaultCalendars()[0];d.week[1]=[[480,720],[600,900]];assert.throws(()=>new WorkCalendar(d),/non-overlapping/);assert.throws(()=>new WorkCalendar({...d,week:Array.from({length:7},()=>[])}),/at least one/);});
test('Continuous calendar uses 1440 work minutes per elapsed civil day',()=>{const c=new WorkCalendar(defaultCalendars()[2]),t=dt('2026-07-10T08:00');assert.equal(c.add(t,1440),t+DAY);assert.equal(c.between(t,t+3*DAY),4320);});
test('FS chain computes exact forward and backward passes',()=>{const p=project();p.activities=[activity('A',2),activity('B',3),activity('M',0)];p.relationships=[link('A','B'),link('B','M')];const s=schedule(p);assert.equal(isoDate(result(s,'A').ef),'2026-07-07T17:00');assert.equal(isoDate(result(s,'B').es),'2026-07-08T08:00');assert.equal(isoDate(result(s,'M').ef),'2026-07-10T17:00');for(const r of s.activities){assert.equal(r.totalFloat,0);assert.equal(r.freeFloat,0);assert.equal(r.critical,true);}});
test('Parallel branch receives analytical total and free float',()=>{const p=project();p.activities=[activity('A',5),activity('B',2),activity('M',0)];p.relationships=[link('A','M'),link('B','M')];const s=schedule(p);assert.equal(result(s,'A').totalFloat,0);assert.equal(result(s,'B').totalFloat,3*480);assert.equal(result(s,'B').freeFloat,3*480);assert.equal(result(s,'B').critical,false);});
test('SS relationship uses predecessor start plus working lag',()=>{const p=project();p.activities=[activity('A',5),activity('B',2)];p.relationships=[link('A','B','SS',480)];const s=schedule(p);assert.equal(isoDate(result(s,'B').es),'2026-07-07T08:00');});
test('FF relationship binds successor finish and works backward through its duration',()=>{const p=project();p.activities=[activity('A',5),activity('B',2)];p.relationships=[link('A','B','FF')];const s=schedule(p);assert.equal(result(s,'B').ef,result(s,'A').ef);assert.equal(isoDate(result(s,'B').es),'2026-07-09T08:00');});
test('SF relationship with a lag constrains successor finish',()=>{const p=project();p.activities=[activity('A',2),activity('B',1)];p.relationships=[link('A','B','SF',5*480)];const s=schedule(p);assert.equal(isoDate(result(s,'B').ef),'2026-07-10T17:00');assert.equal(isoDate(result(s,'B').es),'2026-07-10T08:00');});
test('Negative FS lag overlaps activities without breaking forward inequalities',()=>{const p=project();p.activities=[activity('A',5),activity('B',2)];p.relationships=[link('A','B','FS',-2*480)];const s=schedule(p);assert.equal(isoDate(result(s,'B').es),'2026-07-09T08:00');assert.equal(result(s,'B').ef,result(s,'A').ef);});
test('Lag calendar policy changes multi-calendar results',()=>{const p=project();p.activities=[activity('A',5),activity('B',1,{calendarId:'cal-continuous'})];p.relationships=[link('A','B','FS',480)];p.lagCalendar='predecessor';const before=schedule(p);p.lagCalendar='successor';const after=schedule(p);assert.equal(isoDate(result(before,'B').es),'2026-07-13T17:00');assert.equal(isoDate(result(after,'B').es),'2026-07-11T01:00');});
test('SNET and FNET are honored without violating predecessor bounds',()=>{const p=project();p.activities=[activity('A',2,{constraint:'SNET',constraintDate:dt('2026-07-08T08:00')}),activity('B',1,{constraint:'FNET',constraintDate:dt('2026-07-15T17:00')})];p.relationships=[link('A','B')];const s=schedule(p);assert.equal(result(s,'A').es,dt('2026-07-08T08:00'));assert.equal(result(s,'B').ef,dt('2026-07-15T17:00'));});
test('Earlier required finish produces analytical negative float',()=>{const p=project();p.activities=[activity('A',5)];p.finishBy=dt('2026-07-09T17:00');const s=schedule(p);assert.equal(result(s,'A').totalFloat,-480);assert.equal(s.summary.negative,1);assert.ok(s.diagnostics.some(x=>x.code==='NEGATIVE_FLOAT'));});
test('Finish-on-or-before and equality-window conflicts produce diagnostics',()=>{for(const type of ['FNLT','MFO']){const p=project();p.activities=[activity('A',5,{constraint:type,constraintDate:dt('2026-07-08T17:00')})];const s=schedule(p);assert.equal(result(s,'A').ef,dt('2026-07-10T17:00'));assert.equal(result(s,'A').totalFloat,-960);assert.ok(s.diagnostics.some(d=>d.code==='FINISH_WINDOW'));}});
test('Not-started work is scheduled no earlier than the data date',()=>{const p=project();p.dataDate=dt('2026-07-08T08:00');p.activities=[activity('A',2)];assert.equal(result(schedule(p),'A').es,p.dataDate);});
test('Retained logic fixes actual start but holds remaining work behind unfinished FS predecessor',()=>{const p=project();p.dataDate=dt('2026-07-08T08:00');p.activities=[activity('A',2),activity('B',3,{actualStart:dt('2026-07-07T08:00'),percent:33,remaining:2*480})];p.relationships=[link('A','B')];const s=schedule(p),b=result(s,'B');assert.equal(b.es,dt('2026-07-07T08:00'));assert.equal(b.remainingStart,dt('2026-07-10T08:00'));assert.equal(b.ef,dt('2026-07-13T17:00'));});
test('Actual dates stay fixed and completed activities are not critical',()=>{const p=project();p.dataDate=dt('2026-07-10T17:00');p.activities=[activity('A',2,{actualStart:p.start,actualFinish:dt('2026-07-07T17:00'),remaining:0,percent:100})];const r=result(schedule(p),'A');assert.equal(r.es,p.start);assert.equal(r.ef,dt('2026-07-07T17:00'));assert.equal(r.critical,false);});
test('Out-of-sequence completed actuals produce a relationship conflict',()=>{const p=project();p.dataDate=dt('2026-07-10T17:00');p.activities=[activity('A',2),activity('B',1,{actualStart:p.start,actualFinish:dt('2026-07-06T17:00'),remaining:0,percent:100})];p.relationships=[link('A','B')];assert.ok(schedule(p).diagnostics.some(x=>x.code==='ACTUAL_LOGIC_CONFLICT'));});
test('Future actuals and progress without actual start are rejected',()=>{const p=project();p.activities=[activity('A',2,{percent:10})];assert.throws(()=>schedule(p),/actual start/);p.activities[0].actualStart=p.dataDate+DAY;assert.throws(()=>schedule(p),/after the data date/);});
test('Cycle rejection includes a concrete dependency cycle',()=>{const p=project();p.activities=[activity('A'),activity('B'),activity('C')];p.relationships=[link('A','B'),link('B','C'),link('C','A')];assert.throws(()=>schedule(p),/Dependency cycle: .*A.*B.*C|Dependency cycle: .*B.*C.*A|Dependency cycle: .*C.*A.*B/);});
test('Duplicate IDs, dangling relationships and duplicate edges are rejected',()=>{const p=project();p.activities=[activity('A'),activity('A')];assert.throws(()=>validateProject(p),/duplicate ID/);p.activities=[activity('A'),activity('B')];p.relationships=[link('A','C')];assert.throws(()=>validateProject(p),/unknown activity/);p.relationships=[link('A','B'),{...link('A','B'),id:'different-id'}];assert.throws(()=>validateProject(p),/Duplicate dependency/);});
test('WBS parent cycles are rejected',()=>{const p=project();p.wbs=[{id:'a',code:'a',name:'a',parentId:'b'},{id:'b',code:'b',name:'b',parentId:'a'}];assert.throws(()=>validateProject(p),/WBS contains a cycle/);});
test('Incremental duration edit recalculates only dirty descendants forward',()=>{const p=project();p.activities=[activity('A',3),activity('B',2),activity('X',7),activity('Y',2)];p.relationships=[link('A','B'),link('X','Y')];const engine=new Scheduler();engine.schedule(p);p.activities[0].duration=4*480;p.activities[0].remaining=4*480;const inc=engine.schedule(p),full=schedule(p);assert.equal(inc.stats.mode,'incremental');assert.equal(inc.stats.forwardRecomputed,2);assert.equal(inc.stats.backwardVisited,4);assert.deepEqual(inc.activities,full.activities);});
test('Metadata-only edit reuses forward dates and globally verifies float',()=>{const p=project();p.activities=[activity('A',1),activity('B',1)];p.relationships=[link('A','B')];const e=new Scheduler();e.schedule(p);p.activities[0].notes='A note';const r=e.schedule(p);assert.equal(r.stats.forwardRecomputed,0);assert.equal(r.stats.backwardVisited,2);});
test('Calendar changes invalidate all cached forward dates',()=>{const p=project();p.activities=[activity('A',2)];const e=new Scheduler();e.schedule(p);p.calendars[0].exceptions['2026-07-07']=[];const r=e.schedule(p);assert.equal(r.stats.mode,'full');assert.equal(result(r,'A').ef,dt('2026-07-08T17:00'));});
test('History validates before commit and supports undo/redo branching',()=>{const h=new History({n:1});h.commit('Add',x=>x.n++);assert.equal(h.value.n,2);assert.throws(()=>h.commit('Bad',x=>x.n=-1,x=>{if(x.n<0)throw new Error('invalid');}));assert.equal(h.value.n,2);assert.equal(h.undo(),'Add');assert.equal(h.value.n,1);assert.equal(h.redo(),'Add');assert.equal(h.value.n,2);h.undo();h.commit('Branch',x=>x.n=9);assert.equal(h.redo(),null);});
test('Baseline captures immutable values independently from current project edits',()=>{const p=project();p.activities=[activity('A',2)];const s=schedule(p),b=createBaseline(p,s,'Approved');p.activities[0].duration=8*480;p.activities[0].remaining=8*480;assert.equal(b.activities[0].duration,960);const rows=compareSchedules(p,b,schedule(p));assert.equal(rows[0].finishVariance,6*480);});
test('Schedule comparison reports added and removed stable identities',()=>{const p=project();p.activities=[activity('A',2)];const b=createBaseline(p,schedule(p),'Before');p.activities=[activity('B',3)];const rows=compareSchedules(p,b,schedule(p));assert.equal(rows.find(x=>x.id==='B').added,true);assert.equal(rows.find(x=>x.id==='A').removed,true);});
test('Uniform resource demand, overload and hourly costs are computed from assignments',()=>{const p=project();p.activities=[activity('A',1),activity('B',1)];p.resources=[{id:'R',name:'Crew',role:'Labor',capacity:1,rate:50,calendarId:'cal-office'}];p.assignments=[{id:'x',activityId:'A',resourceId:'R',units:1,actualHours:2},{id:'y',activityId:'B',resourceId:'R',units:1,actualHours:0}];const r=analyzeResources(p,schedule(p)).resources[0];assert.equal(r.remainingHours,16);assert.equal(r.buckets[0].capacity,8);assert.equal(r.buckets[0].overload,8);assert.equal(r.overloadedDays,1);assert.equal(r.budgetCost,800);assert.equal(r.actualCost,100);});
test('Resource holiday capacity does not silently erase scheduled demand',()=>{const p=project();p.activities=[activity('A',1)];const c=structuredClone(p.calendars[0]);c.id='resource-only';c.exceptions['2026-07-06']=[];p.calendars.push(c);p.resources=[{id:'R',name:'Crew',role:'Labor',capacity:1,rate:50,calendarId:c.id}];p.assignments=[{id:'x',activityId:'A',resourceId:'R',units:1,actualHours:0}];const r=analyzeResources(p,schedule(p)).resources[0];assert.equal(r.buckets[0].demand,8);assert.equal(r.buckets[0].capacity,0);assert.equal(r.buckets[0].overload,8);assert.equal(r.peak,Infinity);});
test('CSV handles BOM, escaped quotes, embedded newlines and empty trailing cells',()=>{const text='\uFEFFcode,name,note\r\nA,"A, B","He said ""yes""\nNext line"\r\nB,Name,\r\n';assert.deepEqual(parseCSV(text),[['code','name','note'],['A','A, B','He said "yes"\nNext line'],['B','Name','']]);assert.throws(()=>parseCSV('a,"b'),/unterminated/);});
test('CSV export neutralizes spreadsheet formula-like user text',()=>{const out=parseCSV(toCSV([['=HYPERLINK("bad")','+1','@SUM(A1)','-1',-1,'normal']]));assert.deepEqual(out[0],[`'=HYPERLINK("bad")`,"'+1","'@SUM(A1)","'-1",'-1','normal']);});
test('Seed demonstration is a computed, valid 31-activity network',()=>{const p=createDemoProject(),s=schedule(p);assert.equal(s.activities.length,31);assert.equal(s.relationships.length,39);assert.equal(s.summary.critical,12);assert.equal(isoDate(s.forecastFinish),'2026-12-04T17:00');assert.equal(s.relationships.every(r=>r.satisfied),true);assert.equal(analyzeResources(p,s).totals.overloadedDays,39);});
test('Deterministic randomized DAGs match incremental and fresh recomputation',()=>{let seed=12345;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};for(let trial=0;trial<25;trial++){const p=project();p.activities=Array.from({length:24},(_,i)=>activity('A'+i,1+Math.floor(rand()*7),{calendarId:rand()<.3?'cal-site':'cal-office'}));for(let to=1;to<24;to++)for(let from=Math.max(0,to-4);from<to;from++)if(rand()<.45)p.relationships.push(link('A'+from,'A'+to,['FS','SS','FF','SF'][Math.floor(rand()*4)],(Math.floor(rand()*5)-2)*120));const engine=new Scheduler();engine.schedule(p);const changed=Math.floor(rand()*24);p.activities[changed].duration+=120;p.activities[changed].remaining+=120;const inc=engine.schedule(p),fresh=schedule(p);assert.equal(inc.forecastFinish,fresh.forecastFinish);assert.deepEqual(inc.activities,fresh.activities);assert.ok(inc.relationships.every(r=>r.satisfied));}});
test('A later incremental pass does not mutate previously returned result snapshots',()=>{const p=project();p.activities=[activity('A',1),activity('B',3),activity('C',2)];p.relationships=[link('A','B')];const e=new Scheduler(),first=e.schedule(p),snapshot=structuredClone(first);p.activities[2].remaining+=480;e.schedule(p);assert.deepEqual(first,snapshot);});
test('Project data model rejects unconverted ISO date strings',()=>{const p=project();p.start='2026-07-06T08:00';assert.throws(()=>validateProject(p),/integral civil minutes/);});
test('Workbook import validates baseline date records and scenario recursion',()=>{const p=project();p.activities=[activity('A',1)];p.baselines=[createBaseline(p,schedule(p),'Test')];const w={schemaVersion:1,projects:[p]};assert.equal(validateWorkbook(w),w);p.baselines[0].activities[0].start='corrupt';assert.throws(()=>validateWorkbook(w),/integral civil minutes/);p.baselines=[];const branch=structuredClone(p);branch.scenarios=[{id:'recursive'}];p.scenarios=[{id:'s',name:'Branch',project:branch}];assert.throws(()=>validateWorkbook(w),/recursively/);});
